# Generated by Django 2.2.5 on 2019-09-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('tipo_produto', models.CharField(choices=[('0', 'Eletronico'), ('1', 'Eletrodomestico'), ('3', 'Imovel'), ('4', 'Veiculos'), ('5', 'Roupas'), ('6', 'Esportes')], max_length=10)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('imagem', models.ImageField(blank=True, upload_to='', verbose_name='Imagem')),
                ('link', models.CharField(max_length=20, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Glossário',
            },
        ),
    ]
