# Generated by Django 2.2.3 on 2019-09-18 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0004_auto_20190917_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='vendedor',
        ),
    ]
