# Generated by Django 2.2.3 on 2019-09-18 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programas', '0005_remove_vendas_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='vendido',
            field=models.BooleanField(default=False, verbose_name='Vendido'),
        ),
        migrations.AddField(
            model_name='vendas',
            name='produto_vendido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programas.Produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendas',
            name='vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
